export default {
  BASE_URL: 'https://akashsir.in/myapi/ecom1/api/',
  LOGIN_URL: 'api-login.php',
  SIGNUP_URL: 'api-signup.php',
  LOGINWITHOTP_URL: 'api-login-with-otp.php',
  LOGINOTPRESEND_URL: 'api-resend-otp.php',
  LOGINVERIFYOTP: 'api-verify-otp.php',
  VIEWCATEGORY_URL: 'api-view-category.php',
  VIEWSUBCATEGORYPRODUCT_URL: 'api-view-product.php',
  VIEWALLPRODUCTS_URL: 'api-category-wise-product-list.php',
  HOMEPAGEPRODUCT_URL: 'api-best-sell-product-list.php',
  ADDTOCART_URL: 'api-cart-insert.php',
  CARTITEMREMOVE_URL: 'api-cart-remove-product.php',
  CARTUPDATEITEM_URL: 'api-cart-update.php',
  VIEWCART_URL: 'api-cart-view-order.php',
  REMOVECARTITEM_URL: 'api-cart-remove-product.php',
  ORDER_URL: 'api-add-order.php',
  VIEWORDER_URL: 'api-order-listing.php',
  REMOVEAFTERPLACE_URL: 'api-cart-remove-after-place-order.php',
  CANCLEORDER_URL: 'api-order-remove.php',
  RESENDOTP_URL: 'api-resend-otp.php',
  CHANGEPASSWORD_URL: 'api-change-password.php',
  UPDATEPROFILE_URL: 'api-user-profile-update.php ',
  LOGINWITHSOCIALICON_URL: 'api-user-register.php',
};
